# Generated by Django 3.2.6 on 2021-08-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='recommendation',
            field=models.ManyToManyField(blank=True, related_name='_post_post_recommendation_+', to='post.Post', verbose_name='おすすめ'),
        ),
    ]
