# Generated by Django 3.2.6 on 2021-08-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='見出し'),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='閲覧人数'),
        ),
    ]
